# Generated by Django 4.2.4 on 2023-08-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecommerce',
            name='desc',
        ),
        migrations.AddField(
            model_name='ecommerce',
            name='price',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='ecommerce',
            name='rating',
            field=models.IntegerField(default=1),
        ),
    ]
